### 1. words_list 라는 list 안에 love, hate, I, happy, you, am, birthday, to, from, for, me, **dog** 라는 단어가 차례로 포함되어 있다. 이 단어들을 조합하여 2개의 문장을 만드시오.

In [22]:
import random

words_list = ['love','hate','I','happy','you','am','birthday','to','from','for','me','dog']
len(words_list)

# words_list[2]
print(words_list[random.randrange(1,12)],' ',words_list[random.randrange(1,12)])
print(words_list[random.randrange(1,12)],' ',words_list[random.randrange(1,12)])

I   for
you   dog

### 2. 어느 카페의 메뉴가 4가지 있다. Americano, Cafe latte, Green tea latte, Cafe mocha 각 메뉴의 가격은 3000원, 4000원, 4500원, 5000원일 때, 이 메뉴 목록을 dictionary로 작성하고 Cafe latte와 Cafe mocha 를 주문했을 때 결제액을 계산하는 프로그램을 작성하시오.

In [30]:
dict = {'Americano':3000,'Cafe latte':4000,'Green tea latte':4500,'Cafe mocha':5000}
print(dict)
a = input('선택메뉴 : ')
b = input('선택메뉴 : ')
print('결제금액 : ',dict[a] + dict[b])

{'Americano': 3000, 'Cafe latte': 4000, 'Green tea latte': 4500, 'Cafe mocha': 5000}
선택메뉴 : Cafe latte
선택메뉴 : Cafe mocha
결제금액 :  9000

### 3. 리스트를 원소로 갖는 리스트의 각 원소들의 합을 구하는 프로그램을 작성하시오.

a = [(1,2), (3,4),(6,7),(10,11)]

(hint) for (n1,n2) in a:

In [32]:
a = [[1,2],[3,4],[6,7],[10,11]]
for n1,n2 in a:
    print(n1+n2)

3
7
13
21

### 4. 10~30 사이의 홀수를 출력하는 프로그램을 작성하시오.

In [41]:
for i in range (10,31):
    if i % 2 == 1:
        print(i)

11
13
15
17
19
21
23
25
27
29

0

### 5. 2020년이 윤년인지 검사하는 프로그램을 작성하시오.


*  400 으로 나누어 떨어지는 해는 윤년이다.
*  4로 나누어 떨어지는 해는 윤년이다.
*  4로 나누어 떨어지지만 100으로 나누어 떨어지는 해는 윤년이 아니다.

In [52]:
year = 2020
if year % 400 == 0 and year % 4 == 0:
    print(year,'은 윤년입니다')
elif year % 4 and year % 100 == 0:
    print(year,'은 윤년이 아닙니다')
else:
    print(year,'은 윤년이 아닙니다')

2020 은 윤년이 아닙니다

20